format = """
$time\
$all\
"""

[username]
style_user = "blue bold"
# style_user = "bold orange"
style_root = "purple bold italic"
# format = "[$user]($style) ▻ "
format = "[$user]($style)"
disabled = false

[hostname]
ssh_symbol = '@'

[time]
disabled = false
format = "[ $time ]($style)"
time_format = "%T"
utc_time_offset = "local"
style = "dimmed white"

[directory]
style = "bold cyan"
truncation_length = -1
truncate_to_repo = false

[conda]
style = 'dimmed green'
